# Site settings
title: Context Mapper
description: >
  Context Mapper is an open source project providing a Domain-specific Language (DSL) based on Domain-driven Design (DDD) patterns for context mapping and service decomposition.
lang: en-US

logo: /img/cm.png

baseurl: ""
url: https://contextmapper.org # the base hostname & protocol for your site
git_address: https://github.com/ContextMapper
git_edit_address: https://github.com/ContextMapper/contextmapper.github.io/blob/master

# social
twitter:
  card: "summary_large_image"

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Berlin
defaults:
- scope:
    path: _news
    type: news
  values:
    layout: news
    sectionid: news

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  news:
    permalink: /news/:year/:month/:day/:title/
    output: true
